name: Build React Native App (iOS .app and Android .apk)

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS .app and .ipa
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Skip iOS build if no native folder
        if: ${{ !contains(github.workspace, '/ios') && !exists('ios') }}
        run: |
          echo "No ios/ folder detected—skipping iOS build."
          exit 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1

      - name: Install yarn & deps
        run: |
          npm install -g yarn
          yarn install

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Pods
        run: |
          cd ios
          pod install
          cd ..

      - name: Build .app for Device (arm64)
        run: |
          xcodebuild \
            -workspace ios/YourApp.xcworkspace \
            -scheme YourApp \
            -configuration Release \
            -sdk iphoneos \
            -derivedDataPath ios/build

      - name: Export .app to .ipa
        run: |
          mkdir -p ios-output/Payload
          cp -r ios/build/Build/Products/Release-iphoneos/*.app ios-output/Payload/
          cd ios-output
          zip -r YourApp.ipa Payload

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: ios-output/YourApp.ipa
          
  build-android:
    name: Build Android .apk
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1

      - name: Install deps
        run: |
          npm install -g yarn
          yarn install

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Check and give execute permission to gradlew
        run: |
          if [ -f "android/gradlew" ]; then
            chmod +x android/gradlew
          else
            echo "No gradlew found, skipping Android build."
            exit 0
          fi

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/app-release.apk
