name: Build Android APK and Upload to Release

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-android:
    name: Build Android .apk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.1

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Give gradlew execute permissions
        run: |
          chmod +x android/gradlew

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v2
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
